baseurl = ""
relativeurls=true
languageCode = "en-us"
title = "karlduino"
theme = "hugo-lithium"
googleAnalytics = ""
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_cache$", "\\.knit\\.md$", "\\.utf8\\.md$"]
rssLimit = 30

copyright = "The text in this work is licensed under CC-BY-4.0, https://creativecommons.org/licenses/by/4.0/legalcode; code licensed under the MIT license"

[author]
    name = "Karlduino"

[permalinks]
    post = "/:year/:month/:day/:slug/"

[[menu.main]]
    name = "about"
    url = "https://karlduino.org/about"
[[menu.main]]
    name = "github"
    url = "https://github.com/karlduino"

[markup.goldmark.renderer]
unsafe= true

[params]
    description = "Karlduino: exploring arduino and other electronic stuff"
    fullUrl = "https://karlduino.org"
    githubContentUrl = "https://github.com/karlduino/karlduino.github.io/edit/source/content/"
    customCSS = ["css/custom.css"]

    # options for highlight.js (version, additional languages, and theme)
    highlightjsVersion = "9.12.0"
    highlightjsCDN = "//cdnjs.cloudflare.com/ajax/libs"
    highlightjsLang = ["r", "yaml"]
    highlightjsTheme = "github"

    MathJaxCDN = "//cdnjs.cloudflare.com/ajax/libs"
    MathJaxVersion = "2.7.5"

    # path to the favicon, under "static"
    favicon = "favicon.ico"

    [params.logo]
    url = "karlduino.jpg"
    width = 50
    height = 50
    alt = "Logo"
